import os
from flask import Flask, render_template, request, jsonify

app = Flask(name)

# Route to serve the main user interface
@app.route('/')
def index():
    return render_template('index.html')

# Route to receive coordinates from the frontend javascript
@app.route('/update_location', methods=['POST'])
def update_location():
    try:
        data = request.get_json()
        if not data:
            return jsonify({"status": "error", "message": "No data received"}), 400
        
        latitude = data.get('lat')
        longitude = data.get('lon')
        
        print(f"\n[+] New Location Received!")
        print(f"    Latitude:  {latitude}")
        print(f"    Longitude: {longitude}\n")
        
        # Optional: You can import and pass these variables into your 'location_tool.py' here
        
        return jsonify({"status": "success", "message": "Location updated"}), 200
        
    except Exception as e:
        print(f"[-] Error processing location: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

if name == 'main':
    # Paths to your SSL certificate files generated by generate_cert.sh
    cert_path = 'cert.pem'
    key_path = 'key.pem'
    
    # Check if certificates exist before running to avoid sudden crashes
    if os.path.exists(cert_path) and os.path.exists(key_path):
        print("[*] Starting Flask server with HTTPS encryption...")
        app.run(
            host='0.0.0.0', 
            port=5000, 
            debug=True, 
            ssl_context=(cert_path, key_path)
        )
    else:
        print("[-] Critical Error: SSL certificate files ('cert.pem', 'key.pem') not found!")
        print("[*] Please run your './generate_cert.sh' script first, then try again.")